import * as S from './shape.mjs';
import {Result,rows,key,refkey,edition,canonical,equal,ext,declaration,modes,lookup,cyclic} from './core.mjs';

const RULES=['P-SHAPE','X-MODE','R-SELECTION','R-BINDING','R-TOOL','R-CONTENT','R-COMPATIBILITY'];
const kinds={Tool:S.Tool,Instructions:S.Instructions,Skill:S.Skill};
const assessState={incompatible:'declared','not-provided':'absent',unknown:'unknown','declared-supported':'unchecked',blocked:'unchecked'};
export function validateR(ctx,inventory){
  const r=new Result(ctx.id,'R','unresolved-document',RULES);r.boundary(true);r.prerequisites=[ctx.d];if(ctx.d.verdict!=='pass')r.mark('P-PREREQUISITE','blocked','');modes(ctx,r,'validateR');const interpreted=new Set();
  const state=(p,s,detail=s)=>inventory.states.push({input:ctx.id,pointer:p,state:s,detail});
  if(ctx.error||!S.object(ctx.tree)){for(const q of RULES.filter(x=>x!=='X-MODE'))r.mark(q,'blocked','');return{result:r.finish(),interpreted};}
  if(!S.has(ctx.tree,'runtime')){for(const q of RULES.filter(x=>x!=='X-MODE'))r.mark(q,'excluded','/runtime');return{result:r.finish(),interpreted};}
  const rt=ctx.tree.runtime;r.shape(S.Runtime,rt,'/runtime');if(!S.object(rt)){for(const q of RULES.filter(x=>!['P-SHAPE','X-MODE'].includes(x)))r.mark(q,'blocked','/runtime');return{result:r.finish(),interpreted};}
  const configs=Array.isArray(rt.configurations)?rt.configurations:[],configIds=new Map();if(!Array.isArray(rt.configurations))for(const q of['R-SELECTION','R-BINDING','R-TOOL','R-CONTENT','R-COMPATIBILITY'])r.mark(q,'blocked','/runtime');
  for(const[i,c]of configs.entries())if(typeof c?.id==='string'&&c.id){const p=`/runtime/configurations/${i}`;if(configIds.has(c.id))r.find('R-SELECTION',p,'Duplicate configuration id');configIds.set(c.id,[...(configIds.get(c.id)||[]),{c,p,i}]);}
  if(S.valid(S.Runtime,rt)){state('/runtime/selected',S.has(rt,'selected')?'declared':'absent');for(const[i,c]of configs.entries())if(S.valid(S.Configuration,c)){state(`/runtime/configurations/${i}`,'declared');for(const[j,a]of c.agents.entries())if(S.valid(S.AgentBinding,a)){state(`/runtime/configurations/${i}/agents/${j}/engine`,a.engine===null?'absent':'declared');for(const[k,t]of a.tools.entries())if(S.valid(S.ToolBinding,t))state(`/runtime/configurations/${i}/agents/${j}/tools/${k}/selected`,S.has(t,'selected')?'declared':'absent');}}}
  let selected=null;if(!S.has(rt,'selected'))r.mark('R-COMPATIBILITY','excluded','/runtime');else if(typeof rt.selected!=='string'||!rt.selected){r.mark('R-SELECTION','blocked','/runtime');r.mark('R-COMPATIBILITY','blocked','/runtime');}else{r.mark('R-SELECTION');const found=configIds.get(rt.selected);if(!found){r.find('R-SELECTION','/runtime','Selected configuration does not exist');r.mark('R-COMPATIBILITY','blocked','/runtime');}else if(found.length!==1){r.mark('R-COMPATIBILITY','blocked','/runtime');}else selected=found[0];}

  const graphRows=Array.isArray(ctx.tree.graphs)?ctx.tree.graphs.map((v,i)=>({v,p:`/graphs/${i}`})):null;
  function graphFor(c,p){if(!S.valid(S.Key,c?.graph)){r.mark('R-SELECTION','blocked',p);return null;}if(!graphRows){r.mark('R-SELECTION','blocked',p);return null;}const found=graphRows.filter(g=>S.valid(S.Key,g.v?.definition)&&equal(g.v.definition,c.graph));if(!found.length){r.mark('R-SELECTION');r.find('R-SELECTION',p,'Configuration graph does not exist');return null;}if(found.length!==1){r.mark('R-SELECTION','blocked',p);return null;}if(!declaration(ctx,c.graph,'ControlFlow',r,'R-SELECTION',p))return null;r.mark('R-SELECTION');return found[0];}
  function ref(ctxRef,kind,rule,p,statePointer=p){if(!S.valid(S.Ref,ctxRef)){r.mark(rule,'blocked',p);return null;}r.mark(rule);if(!declaration(ctx,ctxRef,kind,r,rule,p))return null;if(ext(ctxRef)){r.mark(rule,'excluded',p);state(statePointer,'unchecked');return{external:true,ref:ctxRef};}const found=lookup(ctx,ctxRef);return found?{...found,ref:ctxRef}:null;}
  function uniqueEditions(values,rule,p){if(!Array.isArray(values)){r.mark(rule,'blocked',p);return;}const seen=new Set();for(const v of values)if(S.valid(S.Edition,v)){r.mark(rule);const k=edition(v);if(seen.has(k))r.find(rule,p,'Duplicate Edition');seen.add(k);}else r.mark(rule,'blocked',p);}
  function payload(found,kind,rule,requesting){if(!found||found.external)return null;const p=`${found.p}/payload`,type=kinds[kind];interpreted.add(p);r.shape(type,found.v.payload,p);if(!S.object(found.v.payload)){r.mark(rule,'blocked',requesting||p);return null;}return{value:found.v.payload,p,found};}
  function claimMap(claims,rule,p){if(!Array.isArray(claims)){r.mark(rule,'blocked',p);return{map:new Map(),blocked:true};}const map=new Map(),seen=new Set();for(const[i,c]of claims.entries()){const cp=`${p}/claims/${i}`;if(S.valid(S.CapabilityClaim,c)){r.mark(rule);const k=edition(c.capability);if(seen.has(k))r.find(rule,cp,'Duplicate capability claim');seen.add(k);map.set(k,c);if(c.evidence===null)state(`${cp}/evidence`,'unknown');}else r.mark(rule,'blocked',cp);}return{map,blocked:false};}
  function projection(g,cp){if(!g)return null;if(!Array.isArray(g.v.steps)){r.mark('R-BINDING','blocked',cp);return null;}const refs=[];for(const s of g.v.steps){if(!S.object(s)||!['invoke','condition','approval','end'].includes(s.kind)||(s.kind==='invoke'&&!S.valid(S.Ref,s.agent))){r.mark('R-BINDING','blocked',cp);return null;}if(s.kind==='invoke'&&!refs.some(x=>canonical(x)===canonical(s.agent)))refs.push(s.agent);}return refs;}
  const analyses=new Map();
  for(const[ci,c]of configs.entries()){
    const cp=`/runtime/configurations/${ci}`;if(!S.object(c)){for(const q of['R-SELECTION','R-BINDING','R-TOOL','R-CONTENT'])r.mark(q,'blocked',cp);continue;}r.mark('R-SELECTION');const g=graphFor(c,cp),used=projection(g,cp),bindings=Array.isArray(c.agents)?c.agents:[];if(!Array.isArray(c.agents))for(const q of['R-BINDING','R-TOOL','R-CONTENT'])r.mark(q,'blocked',cp);
    const seenAgents=new Set(),bindingBy=new Map();for(const[ai,a]of bindings.entries()){
      const ap=`${cp}/agents/${ai}`;if(!S.object(a)){for(const q of['R-BINDING','R-TOOL','R-CONTENT'])r.mark(q,'blocked',ap);continue;}const agent=ref(a.agent,'Agent','R-BINDING',ap,`${ap}/agent`);if(S.valid(S.Ref,a.agent)){const k=canonical(a.agent);if(seenAgents.has(k))r.find('R-BINDING',ap,'Duplicate AgentBinding');seenAgents.add(k);bindingBy.set(k,{a,ap,agent,ai});}uniqueEditions(a.requires,'R-BINDING',ap);claimMap(a.claims,'R-BINDING',ap);if(a.engine!==null&&!S.valid(S.Edition,a.engine))r.mark('R-BINDING','blocked',ap);else r.mark('R-BINDING');
      if(!Array.isArray(a.tools))r.mark('R-TOOL','blocked',ap);if(!Array.isArray(a.applications))r.mark('R-CONTENT','blocked',ap);
    }
    if(used){r.mark('R-BINDING');const need=new Set(used.map(canonical));if(need.size!==seenAgents.size||[...need].some(k=>!seenAgents.has(k)))r.find('R-BINDING',cp,'AgentBinding coverage differs from graph Agents');}
    analyses.set(c,{cp,g,used,bindingBy});
  }

  function analyzeBinding(item,doAssess){
    const {a,ap,agent}=item;let blocked=false,unknownExternal=false,missingContent=false;const engineReq=new Map(),toolReq=new Map(),content=new Map(),roots=[];
    uniqueEditions(a.requires,'R-BINDING',ap);for(const e of Array.isArray(a.requires)?a.requires:[])if(S.valid(S.Edition,e))engineReq.set(edition(e),e);
    const rels=rows(ctx,'relations',S.Relation).filter(x=>agent&&!agent.external&&S.valid(S.Key,x.v?.source)&&equal(x.v.source,agent.v.key));for(const x of rels){if(x.v.relation==='directedBy'&&['Instructions','Skill'].includes(x.v.expectedKind))roots.push({ref:x.v.target,request:`${x.p}/target`});if(x.v.relation==='uses'&&x.v.expectedKind==='Tool')toolReq.set(canonical(x.v.target),x.v.target);}
    const visiting=new Set(),done=new Set(),edges=[];
    function visit(refValue,request,statePointer=request){const k=canonical(refValue);if(done.has(k))return content.get(k);if(visiting.has(k))return content.get(k);visiting.add(k);const found=ref(refValue,null,'R-CONTENT',request,statePointer);if(found?.external){unknownExternal=true;visiting.delete(k);done.add(k);content.set(k,found);return found;}if(!found){missingContent=true;visiting.delete(k);done.add(k);return null;}const kind=found.v.kind;if(!['Instructions','Skill'].includes(kind)){r.find('R-CONTENT',request,'Content target has wrong kind');missingContent=true;visiting.delete(k);done.add(k);return null;}const pl=payload(found,kind,'R-CONTENT',request);content.set(k,{found,pl,kind,ref:refValue});if(pl){for(const e of Array.isArray(pl.value.requires)?pl.value.requires:[])if(S.valid(S.Edition,e))engineReq.set(edition(e),e);uniqueEditions(pl.value.requires,'R-CONTENT',pl.p);if(kind==='Instructions'&&S.valid(S.Edition,pl.value.format))engineReq.set(edition(pl.value.format),pl.value.format);if(kind==='Skill'){if(!Array.isArray(pl.value.dependencies)){r.mark('R-CONTENT','blocked',pl.p);blocked=true;}else{const seen=new Set();for(const[i,dep]of pl.value.dependencies.entries()){const dk=canonical(dep);if(seen.has(dk))r.find('R-CONTENT',pl.p,'Duplicate Skill dependency');seen.add(dk);edges.push([k,dk]);visit(dep,pl.p,`${pl.p}/dependencies/${i}`);}}if(Array.isArray(pl.value.tools)){const seen=new Set();for(const[i,t]of pl.value.tools.entries()){const tk=canonical(t);if(seen.has(tk))r.find('R-CONTENT',pl.p,'Duplicate Skill Tool');seen.add(tk);ref(t,'Tool','R-CONTENT',pl.p,`${pl.p}/tools/${i}`);toolReq.set(tk,t);}}else{r.mark('R-CONTENT','blocked',pl.p);blocked=true;}}}visiting.delete(k);done.add(k);return content.get(k);}
    for(const root of roots)visit(root.ref,root.request);const adjacency=new Map();for(const[a,b]of edges)adjacency.set(a,[...(adjacency.get(a)||[]),b]);for(const[k,x]of content)if(x?.kind==='Skill'){const seen=new Set(),todo=[...(adjacency.get(k)||[])];let cycle=false;while(todo.length){const n=todo.pop();if(n===k){cycle=true;break;}if(seen.has(n))continue;seen.add(n);todo.push(...(adjacency.get(n)||[]));}if(cycle&&x.pl)r.find('R-CONTENT',x.pl.p,'Skill dependency cycle');}
    const apps=Array.isArray(a.applications)?a.applications:[],appPositions=new Map();for(const[i,x]of apps.entries()){const p=`${ap}/applications/${i}`;if(!S.object(x)){r.mark('R-CONTENT','blocked',p);blocked=true;continue;}if(S.valid(S.Edition,x.adapter))engineReq.set(edition(x.adapter),x.adapter);const f=ref(x.content,null,'R-CONTENT',p,`${p}/content`);if(f?.external)unknownExternal=true;const k=canonical(x.content);appPositions.set(k,[...(appPositions.get(k)||[]),i]);}
    for(const root of roots)if(!appPositions.has(canonical(root.ref))){r.find('R-CONTENT',ap,'Required Application missing');missingContent=true;}for(const[k,x]of content)if(x?.kind==='Skill'&&x.pl&&Array.isArray(x.pl.value.dependencies)&&appPositions.has(k))for(const dep of x.pl.value.dependencies){const dependent=Math.min(...appPositions.get(k)),prior=(appPositions.get(canonical(dep))||[]).some(i=>i<dependent);if(!prior){r.find('R-CONTENT',`${ap}/applications/${dependent}`,'Skill dependency must appear earlier');missingContent=true;}}const reachable=new Set(content.keys());for(const root of roots)reachable.add(canonical(root.ref));for(const[k,positions]of appPositions)if(!reachable.has(k))for(const i of positions)r.find('R-CONTENT',`${ap}/applications/${i}`,'Application is not reachable from Agent direction');
    const tools=Array.isArray(a.tools)?a.tools:[],toolBy=new Map();for(const[i,t]of tools.entries()){const tp=`${ap}/tools/${i}`;if(!S.object(t)){r.mark('R-TOOL','blocked',tp);continue;}const found=ref(t.tool,'Tool','R-TOOL',tp,`${tp}/tool`),k=canonical(t.tool);if(toolBy.has(k))r.find('R-TOOL',tp,'Duplicate ToolBinding');toolBy.set(k,{t,tp,found});const ids=new Set();for(const[j,ch]of(Array.isArray(t.choices)?t.choices:[]).entries()){const ip=`${tp}/choices/${j}`;if(typeof ch?.id==='string'){if(ids.has(ch.id))r.find('R-TOOL',ip,'Duplicate Implementation id');ids.add(ch.id);}claimMap(ch?.claims,'R-TOOL',ip);}if(S.has(t,'selected')&&!ids.has(t.selected))r.find('R-TOOL',tp,'Selected Implementation missing');}
    if(toolReq.size!==toolBy.size||[...toolReq].some(([k])=>!toolBy.has(k)))r.find('R-TOOL',ap,'ToolBinding coverage differs from required Tools');
    for(const[k,refValue]of toolReq){const tb=toolBy.get(k);if(!tb)continue;const pl=payload(tb.found,'Tool','R-TOOL',tb.tp);if(pl){uniqueEditions(pl.value.requires,'R-TOOL',pl.p);if(S.valid(S.Ref,pl.value.action))ref(pl.value.action,'Action','R-TOOL',pl.p,`${pl.p}/action`);if(new Set(pl.value.failures||[]).size!==(pl.value.failures||[]).length)r.find('R-TOOL',pl.p,'Duplicate Tool failure');}if(doAssess)assessTool(tb,pl);}
    if(doAssess)assessAgent();
    function evaluate(requirements,claims,supplied,extraUnknown=false){if(!supplied)return'not-provided';let rank='declared-supported';for(const e of requirements.values()){const c=claims.get(edition(e));if(c?.status==='unsupported')return'incompatible';if(!c||c.status==='unknown'||c.evidence===null)rank='unknown';}return extraUnknown?'unknown':rank;}
    function recordAssessment(p,values,isBlocked=false){r.mark('R-COMPATIBILITY');if(values.includes('incompatible'))r.find('R-COMPATIBILITY',p,'Declared capability incompatible');if(isBlocked){r.mark('R-COMPATIBILITY','blocked',p);state(p,'unchecked','blocked');return;}if(values.some(x=>['not-provided','unknown'].includes(x)))r.find('R-COMPATIBILITY',p,'Compatibility not established','inconclusive');const aggregate=values.includes('incompatible')?'incompatible':values.includes('not-provided')?'not-provided':values.includes('unknown')?'unknown':'declared-supported';state(p,assessState[aggregate],aggregate);}
    function assessAgent(){const claims=claimMap(a.claims,'R-COMPATIBILITY',ap);const values=[evaluate(engineReq,claims.map,a.engine!==null,unknownExternal),...(missingContent?['not-provided']:[])];recordAssessment(ap,values,blocked||claims.blocked);}
    function assessTool(tb,pl){const {t,tp}=tb,choices=Array.isArray(t.choices)?t.choices:[],choice=S.has(t,'selected')?choices.filter(x=>x?.id===t.selected):[];if(choice.length!==1){recordAssessment(tp,['not-provided']);return;}const claims=claimMap(choice[0].claims,'R-COMPATIBILITY',tp),reqs=new Map();for(const e of pl?.value?.requires||[])if(S.valid(S.Edition,e))reqs.set(edition(e),e);recordAssessment(tp,[evaluate(reqs,claims.map,true,tb.found?.external||pl?.value?.effects==='unknown')],claims.blocked);}
  }
  for(const[c,a]of analyses)for(const item of a.bindingBy.values())analyzeBinding(item,selected?.c===c);
  if(selected&&!analyses.get(selected.c)?.bindingBy.size)r.mark('R-COMPATIBILITY');
  return{result:r.finish(),interpreted};
}
